"""README headline numbers must match the surfaces the code actually ships (I1).

README advertised "MCP 28 tools", "38 top-level commands" and a "23 Tools" list
while the shipped surfaces measured 38 MCP tools (real stdio ``tools/list``),
44 top-level / 66 leaf CLI commands, and 30 dashboard HTTP routes. Every number
is now generated by ``scripts/generate_counts.py`` between markers, and this file
fails when a claim drifts.

Two layers are covered:
  * the generated block and the hand-written claim patterns in README, and
  * a real stdio handshake, so the published MCP count describes the tool surface
    as an agent actually discovers it (not just the registry list).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from scripts.generate_counts import (
    BEGIN,
    END,
    README_PATH,
    _mcp_tool_count_over_stdio,
    apply_block,
    check_claims,
    measure,
    render_block,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "generate_counts.py"
HEADER = "README headline counts"


def _readme() -> str:
    return README_PATH.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def counts():
    """Live counts from the registry/CLI/app (no subprocess: fast in every shard)."""
    return measure(prefer_handshake=False)


def test_readme_generated_block_is_current(counts) -> None:
    text = _readme()

    assert BEGIN in text and END in text, "generated count block markers are missing"
    assert render_block(counts) in text, (
        "README surface-count block is stale; run "
        "`python scripts/generate_counts.py --write`"
    )
    assert apply_block(text, render_block(counts)) == text


def test_readme_claims_match_live_counts(counts) -> None:
    problems = check_claims(counts, _readme())

    assert problems == [], (
        f"{HEADER} disagree with the code:\n  - " + "\n  - ".join(problems)
    )


def test_a_wrong_command_count_is_rejected(counts) -> None:
    """The check must actually fail on mismatch, not merely pass today."""
    tampered = _readme().replace("44 top-level commands", "38 top-level commands", 1)

    problems = check_claims(counts, tampered)

    assert any("claims 38" in problem for problem in problems), problems


def test_a_wrong_tool_badge_is_rejected(counts) -> None:
    tampered = _readme().replace("MCP-38%20tools", "MCP-28%20tools", 1)

    problems = check_claims(counts, tampered)

    assert any("MCP badge" in problem and "claims 28" in problem for problem in problems), problems


def test_a_hand_maintained_test_count_is_rejected(counts) -> None:
    """Test pass/skip counts belong to CI, not to the README."""
    anchor = "# Run the test suite (current pass/skip counts: see the CI badge at the top)"
    assert anchor in _readme()

    tampered = _readme().replace(anchor, "# 1534 passed / 12 skipped on Python 3.11", 1)

    problems = check_claims(counts, tampered)

    assert any("hard-coded test pass/skip count" in problem for problem in problems), problems


@pytest.mark.timeout(300)
def test_mcp_tool_count_matches_a_real_stdio_handshake(counts) -> None:
    """The published tool count must equal what ``tools/list`` serves to an agent."""
    pytest.importorskip("mcp", reason="mcp extra not installed")

    from xpst.mcp import server as mcp_server

    served = _mcp_tool_count_over_stdio()

    assert served == len(mcp_server.TOOLS) == counts.mcp_tools
    assert f"| MCP tools | **{served}** |" in _readme()


@pytest.mark.timeout(300)
def test_check_mode_succeeds_on_the_committed_readme() -> None:
    """The CI entry point itself, end to end (includes the stdio handshake)."""
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=280,
    )

    assert proc.returncode == 0, f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
    assert "PASS" in proc.stdout
