"""xPST v1.0.0 — Free, open-source, local-first cross-posting suite.

Distribute short-form video to YouTube, Instagram, X, TikTok, and Threads —
all for free via official APIs. Includes cross-post
correlation, follower tracking, best-time-to-post analytics, a knowledge
base that works with zero config, and an AI agent integration layer
(CLI + MCP).

Key Features:
    - Cross-posting to 5 video platforms (YouTube, IG, X, TikTok, Threads)
    - Official APIs by default, community mode for unofficial (opt-in)
    - Cross-post correlation — one video = one entry with total metrics
    - Follower tracking, best-time-to-post, engagement rate analytics
    - Knowledge base with zero-config deterministic fallback
    - sqlite-vec vector store (<1MB, replaces LanceDB)
    - 24+ MCP tools for AI agent integration
    - 36+ CLI commands with --json
    - PySide6/QML desktop app with accessibility (WCAG AA target)
    - Secure credential storage (Fernet + scrypt, OS keychain)
    - Circuit breaker, retry, crash recovery, graceful shutdown

Quick Start:
    >>> from xpst import XPSTConfig, CrossPostEngine
    >>> config = XPSTConfig.load()
    >>> engine = CrossPostEngine(config)
    >>> results = asyncio.run(engine.check_and_post())
"""

import importlib.metadata


def _resolve_version() -> str:
    """Return the canonical xPST version from the most authoritative source.

    The version MUST NOT drift between the About page / CLI output and the
    bundled app's Info.plist (which reads pyproject.toml at build time). It
    is a single-seeded source of truth, so in no context do we fall back to a
    stale hard-coded literal (which previously reported v1.0.0 while the
    bundle was 1.1.0).

    Resolution order:
      1. ``_build_version`` — generated by build.sh from pyproject.toml and
         shipped inside the frozen bundle. This is the ONLY branch that can
         succeed in a PyInstaller one-folder app, where the xpst distribution
         metadata is not present (importlib.metadata raises
         PackageNotFoundError) yet the bundled version must still match the
         Info.plist exactly.
      2. ``importlib.metadata`` — an installed/editable distribution. Reliable
         only when the installed metadata matches pyproject.toml.
      3. ``pyproject.toml`` next to the package — a bare source checkout
         (``python -m xpst`` without an install).
    """
    # 1) build-time generated source of truth (frozen bundles, post-build).
    try:
        from xpst import _build_version  # type: ignore[import-not-found]

        ver = getattr(_build_version, "__version__", "")
        if ver:
            return ver
    except Exception:  # noqa: BLE001 - any failure just falls through
        pass
    # 2) installed package metadata.
    try:
        return importlib.metadata.version("xpst")
    except importlib.metadata.PackageNotFoundError:
        pass
    # 3) bare source checkout: read pyproject.toml next to the repository.
    try:
        import re
        from pathlib import Path

        pp = Path(__file__).resolve().parents[2] / "pyproject.toml"
        m = re.search(r'^version = "([^"]+)"', pp.read_text(encoding="utf-8"), re.MULTILINE)
        if m:
            return m.group(1)
    except Exception:  # noqa: BLE001
        pass
    # Last resort — a neutral dev marker, never a stale real release.
    return "0.0.0"


__version__ = _resolve_version()
__author__ = "xPST Contributors"

from .config import NotificationConfig, XPSTConfig
from .engine import CrossPostEngine
from .state import StateManager

__all__ = [
    "XPSTConfig",
    "CrossPostEngine",
    "StateManager",
    "NotificationConfig",
]
